### ISSUE TITLE
Bower deprecated in May 2017 and not strictly needed, remove peerDendency

### ISSUE THREAD

**Issue by PeterRJones** [dbkaplun/rolex#6]
Rolex specifies `bower` as a `peerDependency`.  

As a packaging dependency, bower is not required for `rolex` to run properly.  (Our project uses Webpack/Browserify.). As of May 2017 bower has been deprecated as per Issue [#2298](https://github.com/bower/bower/issues/2298) .

Lastly, and perhaps most importantly, if you run `npm ls` it will fail with a non-0 exit code if unfulfilled `peerDepdencies` are found, such as with `rolex`. Perhaps only an annoyance, but if you use `npm ls` to check the consistency of your build tree as part of a deployment pipeline, this error becomes more significant.

Is there anyway to remove the `bower` reference from your peerDependency ?

**Comment by dbkaplun** [comment]
Closed as of [v1.1.1](https://www.npmjs.com/package/rolex).
